apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgenerator
  template:
    metadata:
      labels:
        app: loadgenerator
    spec:
      containers:
        - name: loadgenerator
          image: marypearl/loadgenerator:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: loadgenerator
  namespace: default
spec:
  selector:
    app: loadgenerator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
